# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Deplacement_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DeplacementDialogBase(object):
    def setupUi(self, DeplacementDialogBase):
        DeplacementDialogBase.setObjectName(_fromUtf8("DeplacementDialogBase"))
        DeplacementDialogBase.resize(696, 644)
        self.tabWidget = QtGui.QTabWidget(DeplacementDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 671, 651))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_format_vecteur = QtGui.QGroupBox(self.tab)
        self.groupBox_format_vecteur.setGeometry(QtCore.QRect(10, 309, 571, 101))
        self.groupBox_format_vecteur.setObjectName(_fromUtf8("groupBox_format_vecteur"))
        self.label_taille = QtGui.QLabel(self.groupBox_format_vecteur)
        self.label_taille.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_taille.setObjectName(_fromUtf8("label_taille"))
        self.label_couleur = QtGui.QLabel(self.groupBox_format_vecteur)
        self.label_couleur.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_couleur.setObjectName(_fromUtf8("label_couleur"))
        self.label_base_couleur = QtGui.QLabel(self.groupBox_format_vecteur)
        self.label_base_couleur.setGeometry(QtCore.QRect(100, 50, 41, 16))
        self.label_base_couleur.setObjectName(_fromUtf8("label_base_couleur"))
        self.label_base_taille = QtGui.QLabel(self.groupBox_format_vecteur)
        self.label_base_taille.setGeometry(QtCore.QRect(100, 20, 41, 16))
        self.label_base_taille.setObjectName(_fromUtf8("label_base_taille"))
        self.label_segment = QtGui.QLabel(self.groupBox_format_vecteur)
        self.label_segment.setGeometry(QtCore.QRect(210, 20, 61, 16))
        self.label_segment.setObjectName(_fromUtf8("label_segment"))
        self.label_tete = QtGui.QLabel(self.groupBox_format_vecteur)
        self.label_tete.setGeometry(QtCore.QRect(370, 20, 41, 16))
        self.label_tete.setObjectName(_fromUtf8("label_tete"))
        self.mColorButton_base = gui.QgsColorButton(self.groupBox_format_vecteur)
        self.mColorButton_base.setGeometry(QtCore.QRect(140, 50, 21, 21))
        self.mColorButton_base.setObjectName(_fromUtf8("mColorButton_base"))
        self.spinBox_base_taille = QtGui.QSpinBox(self.groupBox_format_vecteur)
        self.spinBox_base_taille.setGeometry(QtCore.QRect(140, 20, 42, 22))
        self.spinBox_base_taille.setObjectName(_fromUtf8("spinBox_base_taille"))
        self.spinBox_segment = QtGui.QSpinBox(self.groupBox_format_vecteur)
        self.spinBox_segment.setGeometry(QtCore.QRect(280, 20, 42, 22))
        self.spinBox_segment.setObjectName(_fromUtf8("spinBox_segment"))
        self.spinBox_tete = QtGui.QSpinBox(self.groupBox_format_vecteur)
        self.spinBox_tete.setGeometry(QtCore.QRect(410, 20, 42, 22))
        self.spinBox_tete.setObjectName(_fromUtf8("spinBox_tete"))
        self.groupBox_option_champs = QtGui.QGroupBox(self.tab)
        self.groupBox_option_champs.setGeometry(QtCore.QRect(10, 150, 641, 51))
        self.groupBox_option_champs.setObjectName(_fromUtf8("groupBox_option_champs"))
        self.checkBox_ignorer_champs_vides = QtGui.QCheckBox(self.groupBox_option_champs)
        self.checkBox_ignorer_champs_vides.setGeometry(QtCore.QRect(0, 20, 201, 17))
        self.checkBox_ignorer_champs_vides.setObjectName(_fromUtf8("checkBox_ignorer_champs_vides"))
        self.checkBox_virgule_separateur = QtGui.QCheckBox(self.groupBox_option_champs)
        self.checkBox_virgule_separateur.setGeometry(QtCore.QRect(200, 20, 181, 17))
        self.checkBox_virgule_separateur.setObjectName(_fromUtf8("checkBox_virgule_separateur"))
        self.label_ligne_a_ignorer = QtGui.QLabel(self.groupBox_option_champs)
        self.label_ligne_a_ignorer.setGeometry(QtCore.QRect(400, 20, 191, 17))
        self.label_ligne_a_ignorer.setObjectName(_fromUtf8("label_ligne_a_ignorer"))
        self.spinBox_lignes_a_ignorer = QtGui.QSpinBox(self.groupBox_option_champs)
        self.spinBox_lignes_a_ignorer.setGeometry(QtCore.QRect(600, 20, 42, 22))
        self.spinBox_lignes_a_ignorer.setObjectName(_fromUtf8("spinBox_lignes_a_ignorer"))
        self.groupBox_format_fichier = QtGui.QGroupBox(self.tab)
        self.groupBox_format_fichier.setGeometry(QtCore.QRect(10, 100, 571, 51))
        self.groupBox_format_fichier.setObjectName(_fromUtf8("groupBox_format_fichier"))
        self.radioButton_format_csv = QtGui.QRadioButton(self.groupBox_format_fichier)
        self.radioButton_format_csv.setGeometry(QtCore.QRect(110, 20, 82, 17))
        self.radioButton_format_csv.setObjectName(_fromUtf8("radioButton_format_csv"))
        self.radioButton_format_texte = QtGui.QRadioButton(self.groupBox_format_fichier)
        self.radioButton_format_texte.setGeometry(QtCore.QRect(330, 20, 82, 17))
        self.radioButton_format_texte.setObjectName(_fromUtf8("radioButton_format_texte"))
        self.groupBox_selection_fichier = QtGui.QGroupBox(self.tab)
        self.groupBox_selection_fichier.setGeometry(QtCore.QRect(0, 0, 621, 101))
        self.groupBox_selection_fichier.setObjectName(_fromUtf8("groupBox_selection_fichier"))
        self.label_nom_fichier = QtGui.QLabel(self.groupBox_selection_fichier)
        self.label_nom_fichier.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.label_nom_fichier.setObjectName(_fromUtf8("label_nom_fichier"))
        self.lineEdit_nom_couche = QtGui.QLineEdit(self.groupBox_selection_fichier)
        self.lineEdit_nom_couche.setGeometry(QtCore.QRect(170, 70, 271, 20))
        self.lineEdit_nom_couche.setObjectName(_fromUtf8("lineEdit_nom_couche"))
        self.label_nom_couche = QtGui.QLabel(self.groupBox_selection_fichier)
        self.label_nom_couche.setGeometry(QtCore.QRect(10, 70, 131, 21))
        self.label_nom_couche.setObjectName(_fromUtf8("label_nom_couche"))
        self.toolButton_charger_fichier = QtGui.QToolButton(self.groupBox_selection_fichier)
        self.toolButton_charger_fichier.setGeometry(QtCore.QRect(440, 30, 24, 25))
        self.toolButton_charger_fichier.setObjectName(_fromUtf8("toolButton_charger_fichier"))
        self.lineEdit_chemin_fichier = QtGui.QLineEdit(self.groupBox_selection_fichier)
        self.lineEdit_chemin_fichier.setGeometry(QtCore.QRect(140, 30, 281, 27))
        self.lineEdit_chemin_fichier.setObjectName(_fromUtf8("lineEdit_chemin_fichier"))
        self.buttonBox_ok_annuler_tab1 = QtGui.QDialogButtonBox(self.tab)
        self.buttonBox_ok_annuler_tab1.setGeometry(QtCore.QRect(300, 580, 341, 32))
        self.buttonBox_ok_annuler_tab1.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_ok_annuler_tab1.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_ok_annuler_tab1.setObjectName(_fromUtf8("buttonBox_ok_annuler_tab1"))
        self.tableView_format_fichier = QtGui.QTableView(self.tab)
        self.tableView_format_fichier.setGeometry(QtCore.QRect(10, 390, 581, 181))
        self.tableView_format_fichier.setObjectName(_fromUtf8("tableView_format_fichier"))
        self.groupBox_definition_geometrie = QtGui.QGroupBox(self.tab)
        self.groupBox_definition_geometrie.setGeometry(QtCore.QRect(10, 200, 621, 131))
        self.groupBox_definition_geometrie.setObjectName(_fromUtf8("groupBox_definition_geometrie"))
        self.label_champ_X_debut = QtGui.QLabel(self.groupBox_definition_geometrie)
        self.label_champ_X_debut.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_champ_X_debut.setObjectName(_fromUtf8("label_champ_X_debut"))
        self.label_champ_Y_debut = QtGui.QLabel(self.groupBox_definition_geometrie)
        self.label_champ_Y_debut.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_champ_Y_debut.setObjectName(_fromUtf8("label_champ_Y_debut"))
        self.mFieldComboBox_champ_X_debut = gui.QgsFieldComboBox(self.groupBox_definition_geometrie)
        self.mFieldComboBox_champ_X_debut.setGeometry(QtCore.QRect(130, 20, 160, 27))
        self.mFieldComboBox_champ_X_debut.setObjectName(_fromUtf8("mFieldComboBox_champ_X_debut"))
        self.mFieldComboBox_champ_Y_debut = gui.QgsFieldComboBox(self.groupBox_definition_geometrie)
        self.mFieldComboBox_champ_Y_debut.setGeometry(QtCore.QRect(130, 60, 160, 27))
        self.mFieldComboBox_champ_Y_debut.setObjectName(_fromUtf8("mFieldComboBox_champ_Y_debut"))
        self.label_champ_X_fin = QtGui.QLabel(self.groupBox_definition_geometrie)
        self.label_champ_X_fin.setGeometry(QtCore.QRect(330, 20, 111, 16))
        self.label_champ_X_fin.setObjectName(_fromUtf8("label_champ_X_fin"))
        self.mFieldComboBox_champ_X_fin = gui.QgsFieldComboBox(self.groupBox_definition_geometrie)
        self.mFieldComboBox_champ_X_fin.setGeometry(QtCore.QRect(450, 20, 160, 27))
        self.mFieldComboBox_champ_X_fin.setObjectName(_fromUtf8("mFieldComboBox_champ_X_fin"))
        self.mFieldComboBox_champ_Y_fin = gui.QgsFieldComboBox(self.groupBox_definition_geometrie)
        self.mFieldComboBox_champ_Y_fin.setGeometry(QtCore.QRect(450, 60, 160, 27))
        self.mFieldComboBox_champ_Y_fin.setObjectName(_fromUtf8("mFieldComboBox_champ_Y_fin"))
        self.label_champ_Y_fin = QtGui.QLabel(self.groupBox_definition_geometrie)
        self.label_champ_Y_fin.setGeometry(QtCore.QRect(330, 60, 111, 16))
        self.label_champ_Y_fin.setObjectName(_fromUtf8("label_champ_Y_fin"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 390, 581, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 179))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.tableView_format_fichier.raise_()
        self.groupBox_format_vecteur.raise_()
        self.groupBox_option_champs.raise_()
        self.groupBox_format_fichier.raise_()
        self.groupBox_selection_fichier.raise_()
        self.buttonBox_ok_annuler_tab1.raise_()
        self.groupBox_definition_geometrie.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_legende = QtGui.QGroupBox(self.tab_2)
        self.groupBox_legende.setGeometry(QtCore.QRect(0, 80, 661, 511))
        self.groupBox_legende.setObjectName(_fromUtf8("groupBox_legende"))
        self.label_unites = QtGui.QLabel(self.groupBox_legende)
        self.label_unites.setGeometry(QtCore.QRect(10, 40, 46, 13))
        self.label_unites.setObjectName(_fromUtf8("label_unites"))
        self.label_echelle = QtGui.QLabel(self.groupBox_legende)
        self.label_echelle.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_echelle.setObjectName(_fromUtf8("label_echelle"))
        self.label_indiquer_nord = QtGui.QLabel(self.groupBox_legende)
        self.label_indiquer_nord.setGeometry(QtCore.QRect(10, 120, 111, 21))
        self.label_indiquer_nord.setObjectName(_fromUtf8("label_indiquer_nord"))
        self.label_legende = QtGui.QLabel(self.groupBox_legende)
        self.label_legende.setGeometry(QtCore.QRect(10, 160, 61, 21))
        self.label_legende.setObjectName(_fromUtf8("label_legende"))
        self.label_titre = QtGui.QLabel(self.groupBox_legende)
        self.label_titre.setGeometry(QtCore.QRect(320, 160, 46, 13))
        self.label_titre.setObjectName(_fromUtf8("label_titre"))
        self.comboBox_unites = QtGui.QComboBox(self.groupBox_legende)
        self.comboBox_unites.setGeometry(QtCore.QRect(70, 40, 111, 22))
        self.comboBox_unites.setObjectName(_fromUtf8("comboBox_unites"))
        self.comboBox_echelle = QtGui.QComboBox(self.groupBox_legende)
        self.comboBox_echelle.setGeometry(QtCore.QRect(70, 80, 111, 22))
        self.comboBox_echelle.setObjectName(_fromUtf8("comboBox_echelle"))
        self.checkBox_indiquer_nord = QtGui.QCheckBox(self.groupBox_legende)
        self.checkBox_indiquer_nord.setGeometry(QtCore.QRect(160, 120, 21, 17))
        self.checkBox_indiquer_nord.setText(_fromUtf8(""))
        self.checkBox_indiquer_nord.setObjectName(_fromUtf8("checkBox_indiquer_nord"))
        self.lineEdit_legende = QtGui.QLineEdit(self.groupBox_legende)
        self.lineEdit_legende.setGeometry(QtCore.QRect(100, 160, 201, 20))
        self.lineEdit_legende.setObjectName(_fromUtf8("lineEdit_legende"))
        self.lineEdit_titre = QtGui.QLineEdit(self.groupBox_legende)
        self.lineEdit_titre.setGeometry(QtCore.QRect(380, 160, 191, 20))
        self.lineEdit_titre.setObjectName(_fromUtf8("lineEdit_titre"))
        self.listView_couleurs_fleches = QtGui.QListView(self.groupBox_legende)
        self.listView_couleurs_fleches.setGeometry(QtCore.QRect(10, 230, 611, 221))
        self.listView_couleurs_fleches.setObjectName(_fromUtf8("listView_couleurs_fleches"))
        self.pushButton_couleurs_fleches = QtGui.QPushButton(self.groupBox_legende)
        self.pushButton_couleurs_fleches.setGeometry(QtCore.QRect(10, 200, 75, 23))
        self.pushButton_couleurs_fleches.setObjectName(_fromUtf8("pushButton_couleurs_fleches"))
        self.buttonBox_ok_annuler_tab2 = QtGui.QDialogButtonBox(self.groupBox_legende)
        self.buttonBox_ok_annuler_tab2.setGeometry(QtCore.QRect(310, 460, 341, 32))
        self.buttonBox_ok_annuler_tab2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_ok_annuler_tab2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_ok_annuler_tab2.setObjectName(_fromUtf8("buttonBox_ok_annuler_tab2"))
        self.groupBox_facteur = QtGui.QGroupBox(self.tab_2)
        self.groupBox_facteur.setGeometry(QtCore.QRect(0, 10, 651, 71))
        self.groupBox_facteur.setObjectName(_fromUtf8("groupBox_facteur"))
        self.label_facteur_echelle = QtGui.QLabel(self.groupBox_facteur)
        self.label_facteur_echelle.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.label_facteur_echelle.setObjectName(_fromUtf8("label_facteur_echelle"))
        self.doubleSpinBox_facteur_echelle = QtGui.QDoubleSpinBox(self.groupBox_facteur)
        self.doubleSpinBox_facteur_echelle.setGeometry(QtCore.QRect(150, 20, 69, 27))
        self.doubleSpinBox_facteur_echelle.setObjectName(_fromUtf8("doubleSpinBox_facteur_echelle"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))

        self.retranslateUi(DeplacementDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DeplacementDialogBase)

    def retranslateUi(self, DeplacementDialogBase):
        DeplacementDialogBase.setWindowTitle(_translate("DeplacementDialogBase", "Deplacement", None))
        self.groupBox_format_vecteur.setTitle(_translate("DeplacementDialogBase", "Format vecteur", None))
        self.label_taille.setText(_translate("DeplacementDialogBase", "Taille", None))
        self.label_couleur.setText(_translate("DeplacementDialogBase", "Couleur", None))
        self.label_base_couleur.setText(_translate("DeplacementDialogBase", "base", None))
        self.label_base_taille.setText(_translate("DeplacementDialogBase", "base", None))
        self.label_segment.setText(_translate("DeplacementDialogBase", "segment", None))
        self.label_tete.setText(_translate("DeplacementDialogBase", "tête", None))
        self.groupBox_option_champs.setTitle(_translate("DeplacementDialogBase", "Options de champs", None))
        self.checkBox_ignorer_champs_vides.setText(_translate("DeplacementDialogBase", "Ignorer les champs vides", None))
        self.checkBox_virgule_separateur.setText(_translate("DeplacementDialogBase", "Virgule en séparateur", None))
        self.label_ligne_a_ignorer.setText(_translate("DeplacementDialogBase", "Nombre de lignes à ignorer", None))
        self.groupBox_format_fichier.setTitle(_translate("DeplacementDialogBase", "Format de fichier", None))
        self.radioButton_format_csv.setText(_translate("DeplacementDialogBase", "CSV", None))
        self.radioButton_format_texte.setText(_translate("DeplacementDialogBase", "Texte", None))
        self.groupBox_selection_fichier.setTitle(_translate("DeplacementDialogBase", "Séléction du fichier", None))
        self.label_nom_fichier.setText(_translate("DeplacementDialogBase", "Nom de fichier", None))
        self.label_nom_couche.setText(_translate("DeplacementDialogBase", "Nom de la couche", None))
        self.toolButton_charger_fichier.setText(_translate("DeplacementDialogBase", "...", None))
        self.groupBox_definition_geometrie.setTitle(_translate("DeplacementDialogBase", "Définition de géométrie", None))
        self.label_champ_X_debut.setText(_translate("DeplacementDialogBase", "Champ X début", None))
        self.label_champ_Y_debut.setText(_translate("DeplacementDialogBase", "Champ Y début", None))
        self.label_champ_X_fin.setText(_translate("DeplacementDialogBase", "Champ X fin", None))
        self.label_champ_Y_fin.setText(_translate("DeplacementDialogBase", "Champ Y fin", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DeplacementDialogBase", "Tab 1", None))
        self.groupBox_legende.setTitle(_translate("DeplacementDialogBase", "Légende", None))
        self.label_unites.setText(_translate("DeplacementDialogBase", "Unités", None))
        self.label_echelle.setText(_translate("DeplacementDialogBase", "Echelle", None))
        self.label_indiquer_nord.setText(_translate("DeplacementDialogBase", "Indiquer le nord", None))
        self.label_legende.setText(_translate("DeplacementDialogBase", "Légende", None))
        self.label_titre.setText(_translate("DeplacementDialogBase", "Titre", None))
        self.pushButton_couleurs_fleches.setText(_translate("DeplacementDialogBase", "Couleur", None))
        self.groupBox_facteur.setTitle(_translate("DeplacementDialogBase", "Facteur", None))
        self.label_facteur_echelle.setText(_translate("DeplacementDialogBase", "Facteur d\'échelle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DeplacementDialogBase", "Tab 2", None))

from qgis import gui
